steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - artwork-api
      - --runtime=go122
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=ArtworkHandler
      - --region=europe-west1
      - --set-env-vars=SERP_KEY=$_SERP_KEY,VERTEX_PROJECT_ID=$_VERTEX_PROJECT_ID,VERTEX_PROJECT_LOCATION=$_VERTEX_PROJECT_LOCATION
options:
  logging: CLOUD_LOGGING_ONLY